spring.application.name=demo
spring.datasource.url=jdbc:mariadb://localhost:3306/quizdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# WICHTIG: Damit deine Testfragen geladen werden
spring.sql.init.mode=always